---
abstract: "SHARYANTO's temporary namespace for various roles"
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SHARYANTO-Roles
recommends:
  Term::Size: 0
requires:
  Color::ANSI::Util: 0.03
  Locale::Maketext::Lexicon: 0
  Log::Any: 0
  Module::List: 0
  Moo::Role: 0
  Perinci::Object: 0.07
  Term::Detect::Software: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=SHARYANTO-Roles
  homepage: https://metacpan.org/release/SHARYANTO-Roles
  repository: git://github.com/sharyanto/perl-SHARYANTO-Roles.git
version: 0.66
